apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels:
   env: demo
spec:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
     container:
     - image: nginx
       name: nginx
       port:
        - containerPort: 80
          replicas: 3



