apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat
spec:
  replicas: 3
  selector:
    app: tomcat
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:latest 
        ports:
        - containerPort: 8080
